### ISSUE TITLE
Tip for potfolio...

### ISSUE THREAD

**Issue by jki503** [devyoujin/devyoujin.github.io#1]
hi ujin~
i watched your potfolio. it's useful for many people.
I wanna know potfolio of your tip that i can present my self better!

**Comment by devyoujin** [comment]
Hi, @jki503! 🤓
Thank you for creating the first issue for this repository!
Here are some points that you could take into consideration.
1. Which platform?
- [ ] Self-made + [Github pages](https://docs.github.com/en/pages)
- [ ] Template([Jekyll theme](http://jekyllthemes.org/) or [Hugo theme](https://themes.gohugo.io/)) + Github pages
- [ ] Notion
- [ ] [Gitbook](https://docs.gitbook.com/)
- In my case, [my blog](https://dev-ujin.github.io) is made with **Jekyll&Github pages** and [my portfolio](https://dev-ujin.github.io/portfolio) is **self-made** and hosted by **Github pages**. (I strongly recommend you to use template for your blog and customize it with your preferences, not make it from scratch.)
2. What is included?
- [ ] CV
- [ ] Short introduction of your awesome projects
- [ ] Link to social media
- [ ] Contact form ([Formspree](https://formspree.io/) -> It is as easy as google form, but way more decent.)
- [ ] Communication([Disqus](https://disqus.com/) or [Utterances](https://utteranc.es/))
- [ ] ...
3. Something else? (My personal point of view)
- Put information in one page, so that busy recruiters can check your portfolio with less clicks.
- Take visual advantage with images, emojis, [icons](https://fontawesome.com/)
- Look around others portfolio, get some ideas. (I got the idea for my portfolio from [linktree](https://linktr.ee/))
- If you see something good design or good effect but no idea how it is made, use `F12`. 

When you complete your portfolio, please let me know! I am looking forward to yours!

**Comment by jki503** [comment]
Thank you for your considerate comment. I will be a better developer by referring to your comment.
